@startuml

interface PropertyAccessor
interface PropertyEditorRegistry
interface TypeConverter
interface ConfigurablePropertyAccessor
class PropertyEditorRegistrySupport
abstract class TypeConverterSupport
abstract class AbstractPropertyAccessor
abstract class AbstractNestablePropertyAccessor
interface BeanWrapper
class BeanWrapperImpl


ConfigurablePropertyAccessor -up..> PropertyAccessor
ConfigurablePropertyAccessor -up..> PropertyEditorRegistry
ConfigurablePropertyAccessor -up..> TypeConverter
PropertyEditorRegistrySupport -up..> PropertyEditorRegistry
TypeConverterSupport -up..> TypeConverter
TypeConverterSupport -up-|> PropertyEditorRegistrySupport
AbstractPropertyAccessor -up-|> TypeConverterSupport
AbstractPropertyAccessor -up..> ConfigurablePropertyAccessor
AbstractNestablePropertyAccessor -up-|> AbstractPropertyAccessor
BeanWrapper -up-|> ConfigurablePropertyAccessor
BeanWrapperImpl -up-|> AbstractNestablePropertyAccessor
BeanWrapperImpl -up..> BeanWrapper
@enduml