@startuml
interface Servlet
interface ServletConfig
abstract class GenericServlet
abstract class HttpServlet
abstract class HttpServletBean
abstract class FrameworkServlet
class DispatcherServlet

GenericServlet -up..> Servlet
GenericServlet -up..> ServletConfig
HttpServlet -up-|> GenericServlet
HttpServletBean -up-|> HttpServlet
FrameworkServlet -up-|> HttpServletBean
DispatcherServlet -up-|> FrameworkServlet
@enduml